structure(list(url = "https://api.chucknorris.io/jokes/random?category=animal,career,celebrity,dev,fashion,food,history,money,movie,music,science,sport,travel", 
    status_code = 200L, headers = structure(list(date = "Fri, 24 Jul 2020 15:33:28 GMT", 
        `content-type` = "application/json;charset=UTF-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", via = "1.1 vegur", `cf-cache-status` = "DYNAMIC", 
        `cf-request-id` = "04230e4a4800007459e00d7200000001", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        server = "cloudflare", `cf-ray` = "5b7eb323aa297459-IAD", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Fri, 24 Jul 2020 15:33:28 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            via = "1.1 vegur", `cf-cache-status` = "DYNAMIC", 
            `cf-request-id` = "04230e4a4800007459e00d7200000001", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            server = "cloudflare", `cf-ray` = "5b7eb323aa297459-IAD", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.chucknorris.io", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1598196755, class = c("POSIXct", 
        "POSIXt")), name = "__cfduid", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"categories\":[\"celebrity\"],\"created_at\":\"2020-01-05 13:42:28.420821\",\"icon_url\":\"https://assets.chucknorris.host/img/avatar/chuck-norris.png\",\"id\":\"qlg0kzTbS4K_jG1yoNSDEA\",\"updated_at\":\"2020-01-05 13:42:28.420821\",\"url\":\"https://api.chucknorris.io/jokes/qlg0kzTbS4K_jG1yoNSDEA\",\"value\":\"Chuck Norris can understand Charlie Sheen.\"}"), 
    date = structure(1595604808, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.00005, 
    connect = 0.000051, pretransfer = 0.000157, starttransfer = 0.483452, 
    total = 0.483797)), class = "response")
