structure(list(url = "https://icanhazdadjoke.com", status_code = 200L, 
    headers = structure(list(date = "Fri, 24 Jul 2020 15:33:33 GMT", 
        `content-type` = "text/plain", `transfer-encoding` = "chunked", 
        connection = "keep-alive", `cache-control` = "max-age=0, must-revalidate, no-cache, no-store, public, s-maxage=0", 
        `x-frame-options` = "DENY", `x-xss-protection` = "1; mode=block", 
        `cf-cache-status` = "DYNAMIC", `cf-request-id` = "04230e5d9a0000f99534151200000001", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        `strict-transport-security` = "max-age=15552000; includeSubDomains", 
        `x-content-type-options` = "nosniff", server = "cloudflare", 
        `cf-ray` = "5b7eb3429f96f995-YYZ", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Fri, 24 Jul 2020 15:33:33 GMT", 
            `content-type` = "text/plain", `transfer-encoding` = "chunked", 
            connection = "keep-alive", `cache-control` = "max-age=0, must-revalidate, no-cache, no-store, public, s-maxage=0", 
            `x-frame-options` = "DENY", `x-xss-protection` = "1; mode=block", 
            `cf-cache-status` = "DYNAMIC", `cf-request-id` = "04230e5d9a0000f99534151200000001", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            `strict-transport-security` = "max-age=15552000; includeSubDomains", 
            `x-content-type-options` = "nosniff", server = "cloudflare", 
            `cf-ray` = "5b7eb3429f96f995-YYZ", `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.icanhazdadjoke.com", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1598196711, class = c("POSIXct", 
        "POSIXt")), name = "__cfduid", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("How many kids with ADD does it take to change a lightbulb? Let's go ride bikes!"), 
    date = structure(1595604813, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000082, 
    connect = 0.000085, pretransfer = 0.000307, starttransfer = 0.095191, 
    total = 0.14721)), class = "response")
